In [2]:
from pandas import Series,DataFrame
import pandas as pd
obj=Series([1,2,3,4])
print(obj)
print(" ")
print(obj.values)
print(" ")
print(obj.index)

0    1
1    2
2    3
3    4
dtype: int64
 
[1 2 3 4]
 
RangeIndex(start=0, stop=4, step=1)


In [3]:
obj2=Series([12,34,57,88],index=['a','d','b','c'])
obj2

a    12
d    34
b    57
c    88
dtype: int64

In [4]:
print(obj2.index)
print(obj2.b)

Index(['a', 'd', 'b', 'c'], dtype='object')
57


In [5]:
print(obj2['c'])
obj2['a']=100
obj2[['a','b']]

88


a    100
b     57
dtype: int64

In [6]:
print(obj2[obj2>50])
print("")
print(obj2*2)

a    100
b     57
c     88
dtype: int64

a    200
d     68
b    114
c    176
dtype: int64


In [7]:
import numpy as np
np.exp(obj2)

a    2.688117e+43
d    5.834617e+14
b    5.685720e+24
c    1.651636e+38
dtype: float64

In [8]:
print('e' in obj2)
print('b' in obj2)

False
True


In [9]:
sdata= {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3=Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [10]:
states=['California', 'Ohio', 'Oregon', 'Texas']
obj4=Series(sdata,index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [11]:
# The isnull and notnull functions in pandas should be used to detect missing data
print(obj4.isnull())  # or=  pd.isnull(obj4)
print("")
print(obj4.notnull()) # or= pd.notnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool


In [12]:
print(obj3)
print('')
print(obj4)
obj3+obj4

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64


California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [13]:
obj4.name='population'
obj4.index.name='states'
obj4

states
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [14]:
# Series’s index can be altered in place by assignment
obj4.index= ['B', 'S', 'J', 'R']
obj4

B        NaN
S    35000.0
J    16000.0
R    71000.0
Name: population, dtype: float64

In [15]:
#  DATAFRAME

In [16]:
# Construct a DataFrame
data={
    'State':['Ohio','Ohio','Ohio','Nevada','Nevada'],
    'Year':[2000,2001,2001,2001,2002],
    'Pop':[1.5,1.7,3.6,2.4,2.9]
}
frame=DataFrame(data)
frame

State  Year  Pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2001  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [17]:
DataFrame(data,columns=['Year','State','Pop'])

Year   State  Pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2001    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [18]:
frame2=DataFrame(data,columns=['Pop','State','Year','No.'],index=['one','two','three','four','five'])
frame2

Pop   State  Year  No.
one    1.5    Ohio  2000  NaN
two    1.7    Ohio  2001  NaN
three  3.6    Ohio  2001  NaN
four   2.4  Nevada  2001  NaN
five   2.9  Nevada  2002  NaN

In [19]:
print(frame2.columns)
print()
print(frame2.index)

Index(['Pop', 'State', 'Year', 'No.'], dtype='object')

Index(['one', 'two', 'three', 'four', 'five'], dtype='object')


In [20]:
# DataFrame can be retrieved as a Series either by dict-like notation or by attribute
frame2['State']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: State, dtype: object

In [21]:
# you should use .loc for label-based indexing and .iloc for positional indexing.
frame2.loc['three']

Pop       3.6
State    Ohio
Year     2001
No.       NaN
Name: three, dtype: object

In [22]:
frame2['debt']=16.5
frame2

Pop   State  Year  No.  debt
one    1.5    Ohio  2000  NaN  16.5
two    1.7    Ohio  2001  NaN  16.5
three  3.6    Ohio  2001  NaN  16.5
four   2.4  Nevada  2001  NaN  16.5
five   2.9  Nevada  2002  NaN  16.5

In [23]:
frame2['debt']=np.arange(5)
frame2

Pop   State  Year  No.  debt
one    1.5    Ohio  2000  NaN     0
two    1.7    Ohio  2001  NaN     1
three  3.6    Ohio  2001  NaN     2
four   2.4  Nevada  2001  NaN     3
five   2.9  Nevada  2002  NaN     4

In [24]:
# When assigning lists or arrays to a column, the value’s length must match the length
#  of the DataFrame. If you assign a Series, it will be instead conformed exactly to the
#  DataFrame’s index, inserting missing values in any holes

val=Series([-1.2, -1.5, -1.7], index=['two','three','five'])
frame2['debt']=val
frame2


Pop   State  Year  No.  debt
one    1.5    Ohio  2000  NaN   NaN
two    1.7    Ohio  2001  NaN  -1.2
three  3.6    Ohio  2001  NaN  -1.5
four   2.4  Nevada  2001  NaN   NaN
five   2.9  Nevada  2002  NaN  -1.7

In [25]:
frame2['eastern']= frame2.State =='Ohio'
frame2

Pop   State  Year  No.  debt  eastern
one    1.5    Ohio  2000  NaN   NaN     True
two    1.7    Ohio  2001  NaN  -1.2     True
three  3.6    Ohio  2001  NaN  -1.5     True
four   2.4  Nevada  2001  NaN   NaN    False
five   2.9  Nevada  2002  NaN  -1.7    False

In [26]:
'eastern' in frame2.columns

True

In [27]:
del frame2['eastern']

In [28]:
'eastern' in frame2.columns

False

In [29]:
frame2.columns

Index(['Pop', 'State', 'Year', 'No.', 'debt'], dtype='object')

In [30]:
# Another common form of data is a nested dict of dicts format
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
        'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}
       }
frame3=pd.DataFrame(pop)   
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [31]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [32]:
DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [33]:
pdata={
    'Ohio':frame3['Ohio'][:-1],
    'Nevada':frame3['Nevada'][:2]
}
DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [34]:
frame3.index.name='Year' ; frame3.columns.name='State'
frame3

State  Nevada  Ohio
Year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [35]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [36]:
frame2.values

array([[1.5, 'Ohio', 2000, nan, nan],
       [1.7, 'Ohio', 2001, nan, -1.2],
       [3.6, 'Ohio', 2001, nan, -1.5],
       [2.4, 'Nevada', 2001, nan, nan],
       [2.9, 'Nevada', 2002, nan, -1.7]], dtype=object)

In [37]:
# Index Objects
obj=Series(range(3),index=['a','b','c'])
index=obj.index
print(index)
print()
print(index[1:])
index[1]='d' # Index does not support mutable operations


Index(['a', 'b', 'c'], dtype='object')

Index(['b', 'c'], dtype='object')


TypeError: Index does not support mutable operations

In [ ]:
index=pd.Index(np.arange(3))
obj2=Series([1.5, -2.5, 0],index=index)
obj2.index is index

In [39]:
frame3

State  Nevada  Ohio
Year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [40]:
'Ohio' in frame3

True

In [41]:
2003 in frame3.index

False