In [2]:
import numpy as np

data1=[1,4.5,7.55,7]
arr1=np.array(data1)

arr1

array([1.  , 4.5 , 7.55, 7.  ])

In [3]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
print(arr2.shape)

print(arr2.ndim)

print(arr2.dtype)

print(arr1.dtype)

(2, 4)
2
int32
float64


In [5]:
print(np.zeros((2,3)))
print(np.ones(10))
print(np.empty((2,2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[[1.28526346e-311 2.47032823e-322 0.00000000e+000]
  [0.00000000e+000 7.56571287e-307 2.92966904e-033]]

 [[6.56210077e-091 7.92560434e+165 9.99773420e-048]
  [3.21930245e-057 3.99910963e+252 2.46154797e-312]]]


In [6]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
np.eye(3,3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
arr3=np.array([1,2,3],dtype=np.float64)
print(arr3)
arr3.dtype

[1. 2. 3.]


dtype('float64')

In [9]:
# converting dtype
arr=np.ones((2,3))
arr.dtype

intarr=arr.astype(np.int32)
intarr
intarr.dtype
intarr

array([[1, 1, 1],
       [1, 1, 1]])

In [10]:
arr=np.array([2.1,3.7])
arr
arr.astype(np.int32)


array([2, 3])

In [11]:
num_string=np.array(['1','2'],dtype=np.string_)

num_=num_string.astype(np.int32)
num_

array([1, 2])

In [12]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [13]:
d=[1,2,3,4]
data1=np.array(d)
d2=[5,6,7,8]
data2=np.array(d2)
print(data1*data2)
print(data1-data2) #doing batch operations is called vectorization
# Operations between differently sized arrays is called broadcasting

[ 5 12 21 32]
[-4 -4 -4 -4]


In [14]:
#  Basic Indexing and Slicing
arr=np.arange(10)
print(arr[5])
print(arr[2:7])
arr[4:8]=1
arr

5
[2 3 4 5 6]


array([0, 1, 2, 3, 1, 1, 1, 1, 8, 9])

In [15]:
arr_slice=arr[5:8]
arr_slice[1]=12345
arr

array([    0,     1,     2,     3,     1,     1, 12345,     1,     8,
           9])

In [16]:
arr_slice[:]=64
arr

array([ 0,  1,  2,  3,  1, 64, 64, 64,  8,  9])

In [17]:
print(arr)

[ 0  1  2  3  1 64 64 64  8  9]


In [18]:
arr[5:8].copy()

array([64, 64, 64])

In [19]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[1])
arr2d[2][2]

[4 5 6]


9

In [20]:
arr3d=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [21]:
arr3d[0][:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
old_values=arr3d[0][:2].copy()
arr3d[0][:2]=42
print(arr3d)
print(old_values)

[[[42 42 42]
  [42 42 42]
  [ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]


In [23]:
arr3d[0][:2]=old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
arr3d[1, 0, 2]

3

In [25]:
print(arr[1:6])
print(arr2d[:2,:2])
arr2d[:, :1]

[ 1  2  3  1 64]
[[1 2]
 [4 5]]


array([[1],
       [4],
       [7]])

In [26]:
from numpy.random import randn

names=np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data=randn(7,4)
print(names)
data

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


array([[-0.95614403,  0.81225698,  0.23406352,  1.03849875],
       [ 0.98088177,  0.74082621,  0.57316448,  0.97673793],
       [-1.3086504 ,  0.61085986, -0.54050897,  0.76594732],
       [-0.50280147,  0.11246685,  1.34260515,  0.85103505],
       [-0.64236564, -0.17681514,  0.20722561, -1.36915526],
       [-0.98061506, -1.0705055 , -0.70204204,  0.50714454],
       [-0.95655479, -0.39413801,  2.40256908, -0.76528102]])

In [27]:
print(names=='Bob')
print((names=='Bob').dtype)


[ True False False  True False False False]
bool


In [28]:
data[names == 'Bob'] # this can be used to access elements based on rows and columns

array([[-0.95614403,  0.81225698,  0.23406352,  1.03849875],
       [-0.50280147,  0.11246685,  1.34260515,  0.85103505]])

In [29]:
data[names=='Bob',2:] # this can be used to acceselements based on rows and comulumns

array([[0.23406352, 1.03849875],
       [1.34260515, 0.85103505]])

In [30]:
 data[names == 'Bob', 3]

array([1.03849875, 0.85103505])

In [31]:
#  To select everything but 'Bob', you can either use != or negate the condition using -
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [32]:
data[~(names == 'Bob')]

array([[ 0.98088177,  0.74082621,  0.57316448,  0.97673793],
       [-1.3086504 ,  0.61085986, -0.54050897,  0.76594732],
       [-0.64236564, -0.17681514,  0.20722561, -1.36915526],
       [-0.98061506, -1.0705055 , -0.70204204,  0.50714454],
       [-0.95655479, -0.39413801,  2.40256908, -0.76528102]])

In [33]:
mask= (names=='Bob')|(names=='Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [34]:
data[mask]

array([[-0.95614403,  0.81225698,  0.23406352,  1.03849875],
       [-1.3086504 ,  0.61085986, -0.54050897,  0.76594732],
       [-0.50280147,  0.11246685,  1.34260515,  0.85103505],
       [-0.64236564, -0.17681514,  0.20722561, -1.36915526]])

In [35]:
data[data<0]=0
data

array([[0.        , 0.81225698, 0.23406352, 1.03849875],
       [0.98088177, 0.74082621, 0.57316448, 0.97673793],
       [0.        , 0.61085986, 0.        , 0.76594732],
       [0.        , 0.11246685, 1.34260515, 0.85103505],
       [0.        , 0.        , 0.20722561, 0.        ],
       [0.        , 0.        , 0.        , 0.50714454],
       [0.        , 0.        , 2.40256908, 0.        ]])

In [36]:
data[names!='Joe']=7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.98088177, 0.74082621, 0.57316448, 0.97673793],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.50714454],
       [0.        , 0.        , 2.40256908, 0.        ]])

In [43]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [47]:
print(arr[[1,3,5,7,]])
print('')
print(arr[[-1,-4]])

[[1. 1. 1. 1.]
 [3. 3. 3. 3.]
 [5. 5. 5. 5.]
 [7. 7. 7. 7.]]

[[7. 7. 7. 7.]
 [4. 4. 4. 4.]]


In [49]:
arr=np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [51]:
arr[[2,5,7,0],[0,2,1,3]]

array([ 8, 22, 29,  3])

In [58]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [61]:
# Another way is to use the np.ix_ function, which converts two 1D integer arrays to an
# indexer that selects the square region
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [64]:
#  Transposing Arrays and Swapping Axes
arr=np.arange(15).reshape(3,5)
print(arr)
print('')
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [68]:
# When doing matrix computations, you will do this very often, like for example com
# puting the inner matrix product X(T)X using np.dot
arr = np.random.randn(6, 3)
np.dot(arr.T,arr)


array([[ 3.51694317,  1.29650327, -0.53044135],
       [ 1.29650327,  3.06259785, -0.11338082],
       [-0.53044135, -0.11338082,  7.88243766]])

In [71]:
#  For higher dimensional arrays, transpose will accept a tuple of axis numbers to permute
#  the axes (for extra mind bending)
arr=np.arange(16).reshape(2,2,4)
print(arr)
print(arr.transpose((1,0,2)))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [72]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [75]:
# Universal Functions: Fast Element-wise Array Functions ex: sqrt,exp
arr=np.arange(10)
print(np.sqrt(arr))
print('')
print(np.exp(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [80]:
x=randn(10)
y=randn(10)
print(x)
print(y)
print(np.maximum(x,y))
np.add(x,y)

[ 0.45332989  1.52783276 -0.65606461 -0.11268299 -0.05134179 -0.05490111
  0.68150747  1.25104606  0.70713733  0.25739464]
[ 0.4834868   1.12216641 -0.10436215 -1.15731997 -0.14729104  0.49407403
  0.47523712 -0.08220416  0.86393544  0.00482839]
[ 0.4834868   1.52783276 -0.10436215 -0.11268299 -0.05134179  0.49407403
  0.68150747  1.25104606  0.86393544  0.25739464]


array([ 0.93681669,  2.64999917, -0.76042676, -1.27000297, -0.19863283,
        0.43917292,  1.15674459,  1.1688419 ,  1.57107277,  0.26222304])

In [82]:
#modf is one example, a vectorized version of the built-in Python divmod: it returns the fractional and integral parts of a floating point array
arr=randn(7)*5
np.modf(arr)

(array([ 0.60575037, -0.00975788,  0.38915877,  0.86473781,  0.53167082,
         0.06818769,  0.95340273]),
 array([10., -6.,  3.,  1.,  1.,  8.,  3.]))